[package]
name = "talpid-core"
version = "0.1.0"
authors = ["Mullvad VPN"]
description = "Privacy preserving and secure VPN client library"
license = "GPL-3.0"
edition = "2018"
publish = false

[dependencies]
atty = "0.2"
cfg-if = "0.1"
duct = "0.13"
err-derive = "0.2.1"
futures = "0.1"
hex = "0.4"
ipnetwork = "0.15"
jsonrpc-core = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
jsonrpc-macros = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
lazy_static = "1.0"
libc = "0.2.20"
log = "0.4"
openvpn-plugin = { git = "https://github.com/mullvad/openvpn-plugin-rs", branch = "auth-failed-event", features = ["serde"] }
os_pipe = "0.8"
parking_lot = "0.9"
regex = "1.1.0"
shell-escape = "0.1"
talpid-ipc = { path = "../talpid-ipc" }
talpid-types = { path = "../talpid-types" }
tokio-core = "0.1"
tokio-executor = "0.1"
uuid = { version = "0.7", features = ["v4"] }
zeroize = "1"
chrono = "0.4"


[target.'cfg(unix)'.dependencies]
nix = "0.17"
tokio-process = "0.2"
tokio-io = "0.1"


[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.2.2", features = ["derive"] }
rand = "0.7"


[target.'cfg(target_os = "linux")'.dependencies]
dbus = "0.6"
failure = "0.1"
notify = "4.0"
resolv-conf = "0.6.1"
rtnetlink = { git = "https://github.com/mullvad/netlink", rev = "f768adfcc8c6b064ef7ae3c792c4c21d0d96d0b5" }
netlink-proto = { git = "https://github.com/mullvad/netlink", rev = "f768adfcc8c6b064ef7ae3c792c4c21d0d96d0b5" }
netlink-packet = { git = "https://github.com/mullvad/netlink", rev = "f768adfcc8c6b064ef7ae3c792c4c21d0d96d0b5" }
netlink-sys = { git = "https://github.com/mullvad/netlink", rev = "f768adfcc8c6b064ef7ae3c792c4c21d0d96d0b5" }
nftnl = { git = "https://github.com/mullvad/nftnl-rs", rev = "b8aaf7f882f83235b58e8cd48d3022801d77a1b3", features = ["nftnl-1-1-0"] }
mnl = { version = "0.2.0", features = ["mnl-1-0-4"] }
which = { version = "3.1", default-features = false }
tun = "0.4.3"


[target.'cfg(target_os = "macos")'.dependencies]
pfctl = "0.3"
system-configuration = "0.3"
tun = "0.4.3"


[target.'cfg(windows)'.dependencies]
widestring = "0.4"
winreg = "0.6"
winapi = { version = "0.3.6", features = ["handleapi", "ifdef", "libloaderapi", "netioapi", "synchapi", "winbase", "winuser"] }
socket2 = "0.3"
rand = "0.7"
pnet_packet = "0.22"

[dev-dependencies]
tempfile = "3.0"
