[package]
name = "mullvad-exclude"
version = "0.1.0"
authors = ["Mullvad VPN"]
license = "GPL-3.0"
edition = "2018"
publish = false

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.17"
err-derive = "0.2.1"
void = "1.0.2"
